### ISSUE TITLE
Startup freeze 1.16.3

### ISSUE THREAD

**Issue by lokka30** [funkemunky/Atlas#18]
I'm left with the `Starting scanner...` message on startup, server won't continue loading from there.
Paper 1.16.3 build 202 with Kaui's trial version.

**Comment by Mapacheee** [comment]
The same thing happens to me, I thought it was a heavy process or something like that, but it has been there for 3 hours

**Comment by AgentLoneStar007** [comment]
Same thing here. I had to kill my server, and it output about 607 lines of errors. Not really fun to look through. Please fix this issue soon.

**Comment by Ricozaur** [comment]
I have it too, but with no error's.

**Comment by funkemunky** [comment]
Yes this has been resolved in the latest update
