### ISSUE TITLE
Tnt issue

### ISSUE THREAD

**Issue by Kahouk** [funkemunky/Atlas#22]
When using atlas on factions it for some reason tracks all the tnt entities which creates 2 issues: Tps drops by a significant rate even after the cannoning stopped and tnt pieces themselves get stored at a rate of around 100mb per 500k pieces of tnt. https://timings.aikar.co/?id=778c0150ab304aee8fe430fa0c77de65 search up atlas and you will see on the timings report  that the task Atlas::Task: cc.funkemunky.api.Atlas$$Lambda$485/1261352406 (interval:5) is causing 376% of all server tics from just 537 which causes huge tps issues. Any fix?

**Comment by funkemunky** [comment]
Fixed
