### ISSUE TITLE
Unable to use WrappedOutSpawnLivingEntityPacket wrapper

### ISSUE THREAD

**Issue by BerryThDev** [funkemunky/Atlas#36]
When I try to listen for the living entity spawn packet and then apply the WrappedOutSpawnLivingEntityPacket wrapper to the packet it puts the following error into the console: https://pastebin.com/0FVfA5ev even if I do not access any of it's fields that is just when creating a new instance of the wrapper.

Atlas version: 1.11.5
Server version: 1.8.8

**Comment by funkemunky** [comment]
I'll see if I can fix this for you now
