### ISSUE TITLE
Server freeze

### ISSUE THREAD

**Issue by DeWilX** [funkemunky/Atlas#7]
I'm getting server freeze when player kills another player.
Atlas version - 1.4.6

Errors: https://pastebin.com/qW1mM6T8
Config: https://pastebin.com/aAx6yC1q

Server version - CraftBukkit version git-TacoSpigot-bf023c7d (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

EDIT: Updated to 1.4.7 version still getting this - https://pastebin.com/tgHwsBux

**Comment by funkemunky** [comment]
What plugins are you using with this?

**Comment by funkemunky** [comment]
By that, I mean what plugins are depending on Atlsa.

**Comment by DeWilX** [comment]
> By that, I mean what plugins are depending on Atlsa.

Iris 2.0.1

**Comment by funkemunky** [comment]
Fixed, old Issue.
